# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vending_machine.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vending_machine_0_0/design_1_vending_machine_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vending_machine_0_0 || ORIG_REF_NAME==design_1_vending_machine_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_generator_0_0/design_1_pulse_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_generator_0_0 || ORIG_REF_NAME==design_1_pulse_generator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_generator_0_1/design_1_pulse_generator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_generator_0_1 || ORIG_REF_NAME==design_1_pulse_generator_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_generator_0_2/design_1_pulse_generator_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_generator_0_2 || ORIG_REF_NAME==design_1_pulse_generator_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_generator_2_0/design_1_pulse_generator_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_generator_2_0 || ORIG_REF_NAME==design_1_pulse_generator_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_detector_0_0/design_1_pulse_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_detector_0_0 || ORIG_REF_NAME==design_1_pulse_detector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_detector_0_1/design_1_pulse_detector_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_detector_0_1 || ORIG_REF_NAME==design_1_pulse_detector_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_detector_0_2/design_1_pulse_detector_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_detector_0_2 || ORIG_REF_NAME==design_1_pulse_detector_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_detector_0_3/design_1_pulse_detector_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_detector_0_3 || ORIG_REF_NAME==design_1_pulse_detector_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_5/design_1_debouncer_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_5 || ORIG_REF_NAME==design_1_debouncer_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_1_0 || ORIG_REF_NAME==design_1_debouncer_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_2_0/design_1_debouncer_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_2_0 || ORIG_REF_NAME==design_1_debouncer_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_3_0/design_1_debouncer_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_3_0 || ORIG_REF_NAME==design_1_debouncer_3_0} -quiet] -quiet

# XDC: c:/Users/joshu/Desktop/exercise_5/vending_machine_system/vending_machine_system.gen/sources_1/bd/design_1/design_1_ooc.xdc
