-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity debouncer is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    btn_in : IN STD_LOGIC_VECTOR (0 downto 0);
    btn_out : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of debouncer is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "debouncer_debouncer,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.339925,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=34,HLS_SYN_LUT=190,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_0_1 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_0_2 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv31_98967F : STD_LOGIC_VECTOR (30 downto 0) := "0000000100110001001011001111111";
    constant ap_const_lv31_0_3 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_0_4 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";

    signal state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal counter : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal add_ln46_fu_97_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_empty_phi_fu_64_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal state_load_load_fu_70_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal btn_in_read_read_fu_46_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln45_fu_91_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln48_fu_110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_condition_63 : BOOLEAN;
    signal ap_condition_34 : BOOLEAN;
    signal ap_condition_56 : BOOLEAN;
    signal ap_condition_47 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    counter_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                if ((ap_const_boolean_1 = ap_condition_56)) then 
                    counter <= ap_const_lv31_98967F;
                elsif (((btn_in_read_read_fu_46_p2 = ap_const_lv1_0) and (state_load_load_fu_70_p1 = ap_const_lv2_2))) then 
                    counter <= ap_const_lv31_0_4;
                elsif ((ap_const_boolean_1 = ap_condition_34)) then 
                    counter <= add_ln46_fu_97_p2;
                elsif (((btn_in_read_read_fu_46_p2 = ap_const_lv1_0) and (state_load_load_fu_70_p1 = ap_const_lv2_1))) then 
                    counter <= ap_const_lv31_0_3;
                end if;
            end if; 
        end if;
    end process;

    state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                if ((ap_const_boolean_1 = ap_condition_56)) then 
                    state <= ap_const_lv2_1;
                elsif (((btn_in_read_read_fu_46_p2 = ap_const_lv1_0) and (state_load_load_fu_70_p1 = ap_const_lv2_2))) then 
                    state <= ap_const_lv2_0_2;
                elsif ((ap_const_boolean_1 = ap_condition_47)) then 
                    state <= ap_const_lv2_2;
                elsif (((btn_in_read_read_fu_46_p2 = ap_const_lv1_0) and (state_load_load_fu_70_p1 = ap_const_lv2_1))) then 
                    state <= ap_const_lv2_0_1;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln46_fu_97_p2 <= std_logic_vector(unsigned(counter) + unsigned(ap_const_lv31_7FFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_condition_34_assign_proc : process(state_load_load_fu_70_p1, btn_in_read_read_fu_46_p2, icmp_ln45_fu_91_p2)
    begin
                ap_condition_34 <= ((icmp_ln45_fu_91_p2 = ap_const_lv1_0) and (btn_in_read_read_fu_46_p2 = ap_const_lv1_1) and (state_load_load_fu_70_p1 = ap_const_lv2_1));
    end process;


    ap_condition_47_assign_proc : process(state_load_load_fu_70_p1, btn_in_read_read_fu_46_p2, icmp_ln48_fu_110_p2)
    begin
                ap_condition_47 <= ((icmp_ln48_fu_110_p2 = ap_const_lv1_1) and (btn_in_read_read_fu_46_p2 = ap_const_lv1_1) and (state_load_load_fu_70_p1 = ap_const_lv2_1));
    end process;


    ap_condition_56_assign_proc : process(state_load_load_fu_70_p1, btn_in_read_read_fu_46_p2)
    begin
                ap_condition_56 <= (not((state_load_load_fu_70_p1 = ap_const_lv2_2)) and not((state_load_load_fu_70_p1 = ap_const_lv2_1)) and (btn_in_read_read_fu_46_p2 = ap_const_lv1_1));
    end process;


    ap_condition_63_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_70_p1, btn_in_read_read_fu_46_p2)
    begin
                ap_condition_63 <= ((btn_in_read_read_fu_46_p2 = ap_const_lv1_1) and (state_load_load_fu_70_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_phi_mux_empty_phi_fu_64_p4_assign_proc : process(counter, add_ln46_fu_97_p2, icmp_ln45_fu_91_p2, ap_condition_63)
    begin
        if ((ap_const_boolean_1 = ap_condition_63)) then
            if ((icmp_ln45_fu_91_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_empty_phi_fu_64_p4 <= counter;
            elsif ((icmp_ln45_fu_91_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_empty_phi_fu_64_p4 <= add_ln46_fu_97_p2;
            else 
                ap_phi_mux_empty_phi_fu_64_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_empty_phi_fu_64_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    btn_in_read_read_fu_46_p2 <= btn_in;

    btn_out_assign_proc : process(ap_CS_fsm_state1, state_load_load_fu_70_p1)
    begin
        if (((state_load_load_fu_70_p1 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            btn_out <= ap_const_lv1_1;
        elsif (((not((state_load_load_fu_70_p1 = ap_const_lv2_2)) and not((state_load_load_fu_70_p1 = ap_const_lv2_1)) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((state_load_load_fu_70_p1 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            btn_out <= ap_const_lv1_0;
        else 
            btn_out <= "X";
        end if; 
    end process;

    icmp_ln45_fu_91_p2 <= "1" when (counter = ap_const_lv31_0) else "0";
    icmp_ln48_fu_110_p2 <= "1" when (ap_phi_mux_empty_phi_fu_64_p4 = ap_const_lv31_0) else "0";
    state_load_load_fu_70_p1 <= state;
end behav;
