# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/joshu/Desktop/exercise_5/vending_machine_system/vending_machine_system.srcs/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/design_1_pulse_detector_0_0.xci
# IP: The module: 'design_1_pulse_detector_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joshu/Desktop/exercise_5/vending_machine_system/vending_machine_system.gen/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/constraints/pulse_detector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pulse_detector_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/joshu/Desktop/exercise_5/vending_machine_system/vending_machine_system.srcs/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/design_1_pulse_detector_0_0.xci
# IP: The module: 'design_1_pulse_detector_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/joshu/Desktop/exercise_5/vending_machine_system/vending_machine_system.gen/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/constraints/pulse_detector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pulse_detector_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
