// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="debouncer_debouncer,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.339925,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=34,HLS_SYN_LUT=190,HLS_VERSION=2024_1}" *)

module debouncer (
        ap_clk,
        ap_rst,
        btn_in,
        btn_out
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [0:0] btn_in;
output  [0:0] btn_out;

reg[0:0] btn_out;

reg   [1:0] state;
reg   [30:0] counter;
wire   [30:0] add_ln46_fu_97_p2;
reg   [30:0] ap_phi_mux_empty_phi_fu_64_p4;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] state_load_load_fu_70_p1;
wire   [0:0] btn_in_read_read_fu_46_p2;
wire   [0:0] icmp_ln45_fu_91_p2;
wire   [0:0] icmp_ln48_fu_110_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_condition_63;
reg    ap_condition_34;
reg    ap_condition_56;
reg    ap_condition_47;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 state = 2'd0;
#0 counter = 31'd0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_56)) begin
            counter <= 31'd9999999;
        end else if (((btn_in_read_read_fu_46_p2 == 1'd0) & (state_load_load_fu_70_p1 == 2'd2))) begin
            counter <= 31'd0;
        end else if ((1'b1 == ap_condition_34)) begin
            counter <= add_ln46_fu_97_p2;
        end else if (((btn_in_read_read_fu_46_p2 == 1'd0) & (state_load_load_fu_70_p1 == 2'd1))) begin
            counter <= 31'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_56)) begin
            state <= 2'd1;
        end else if (((btn_in_read_read_fu_46_p2 == 1'd0) & (state_load_load_fu_70_p1 == 2'd2))) begin
            state <= 2'd0;
        end else if ((1'b1 == ap_condition_47)) begin
            state <= 2'd2;
        end else if (((btn_in_read_read_fu_46_p2 == 1'd0) & (state_load_load_fu_70_p1 == 2'd1))) begin
            state <= 2'd0;
        end
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_condition_63)) begin
        if ((icmp_ln45_fu_91_p2 == 1'd1)) begin
            ap_phi_mux_empty_phi_fu_64_p4 = counter;
        end else if ((icmp_ln45_fu_91_p2 == 1'd0)) begin
            ap_phi_mux_empty_phi_fu_64_p4 = add_ln46_fu_97_p2;
        end else begin
            ap_phi_mux_empty_phi_fu_64_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_empty_phi_fu_64_p4 = 'bx;
    end
end

always @ (*) begin
    if (((state_load_load_fu_70_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state1))) begin
        btn_out = 1'd1;
    end else if (((~(state_load_load_fu_70_p1 == 2'd2) & ~(state_load_load_fu_70_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)) | ((state_load_load_fu_70_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        btn_out = 1'd0;
    end else begin
        btn_out = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_fu_97_p2 = ($signed(counter) + $signed(31'd2147483647));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_condition_34 = ((icmp_ln45_fu_91_p2 == 1'd0) & (btn_in_read_read_fu_46_p2 == 1'd1) & (state_load_load_fu_70_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_47 = ((icmp_ln48_fu_110_p2 == 1'd1) & (btn_in_read_read_fu_46_p2 == 1'd1) & (state_load_load_fu_70_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_56 = (~(state_load_load_fu_70_p1 == 2'd2) & ~(state_load_load_fu_70_p1 == 2'd1) & (btn_in_read_read_fu_46_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_63 = ((btn_in_read_read_fu_46_p2 == 1'd1) & (state_load_load_fu_70_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state1));
end

assign btn_in_read_read_fu_46_p2 = btn_in;

assign icmp_ln45_fu_91_p2 = ((counter == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_110_p2 = ((ap_phi_mux_empty_phi_fu_64_p4 == 31'd0) ? 1'b1 : 1'b0);

assign state_load_load_fu_70_p1 = state;

endmodule //debouncer
